// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrder = "orders"

// Order mapped from table <orders>
type Order struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID      int64          `gorm:"column:user_id;not null" json:"user_id"`
	OrderNumber string         `gorm:"column:order_number;not null" json:"order_number"`
	TotalAmount float64        `gorm:"column:total_amount;not null;default:0.00" json:"total_amount"`
	Status      string         `gorm:"column:status;not null;default:pending" json:"status"`
	CreatedAt   *time.Time     `gorm:"column:created_at;<-:create;autoCreateTime" json:"created_at"`
	UpdatedAt   *time.Time     `gorm:"column:updated_at;<-:update;autoUpdateTime" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
